// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "forestMonkey0":return img`
........................
...........ff...........
..........fef...........
.........fef............
........fffff...........
.......feeeeef..........
......fddddeeef.........
.....cdfddfdeeff........
.....cdfddfdeeddf.......
....cdeeddddeebdc.......
....cdddddddeebdc.ff....
....ccccccddeefc.fef....
.....fdddddeeff..fef....
......fffffeeeef.fef....
........feeeeeeeffef....
.......feffefeeeeff.....
.......feffefeeeef......
.......fdbfdbffef.......
.......fddcddbbdf.......
........fffffffff.......
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
........................
........................
........................
........ff..............
........fef.............
.........fef............
........fffff...........
.......feeeeef..........
......feeeddddf.........
.....ffeedfddfdc........
....fddeedfddfdc........
....cdbeeddddeedc.......
.ff.cdbeedddddddc.......
.fef.cfeeddcccccc.......
.fef..ffeedddddf........
.fef.feeeefffff.........
.feffeeeeeeef...........
..ffeeeefeffef..........
...feeeefeffef..........
....feffbdfbdf..........
....fdbbddcddf..........
....fffffffff...........
........................
........................
`, img`
........................
........................
........................
........ff..............
........fef.............
.........fef............
........fffff...........
.......feeeeef..........
......feeeddddf.........
......feedfddfdc........
.....ffeedfddfdc........
....fddeeddddeedc.......
....cdbeedddddddc.......
.ff.cdbeeedcccccc.......
.fef.cffeeeddddf........
.fef.feeeeffffff........
.feffeeeeeeeffff........
..ffeeeefefddfddf.......
...feeeefefbdfbdf.......
...feffffffffffff.......
...fddcf................
...ffff.................
........................
........................
`, img`
........................
........................
........................
........ff..............
........fef.............
.........fef............
........fffff...........
.......feeeeef..........
.....ffeeeddddf.........
....fddeeddddddc........
....cdbeedfddfdc........
.ff.cdbeedfddfddc.......
.fef.cfeeddddeedc.......
.fef..feeeddddddc.......
.fef..ffeeeccccf........
.fef.feeeefffff.........
..fffeeeeeeef...........
...feeeefeefeff.........
...feeefffeeffef........
..fbffffffcddbddf.......
..fddcf..fdddcddf.......
...fff...fffffff........
........................
........................
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
